books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

books/store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("search/", views.search, name="search"),
    path("cart/", views.cart, name="cart"),
    path("book/<int:bookID>/", views.book, name="book"),
    path("checkout", views.checkout, name="checkout"),
    path("purchases", views.purchases, name="purchases"),
    path("account", views.view_account, name="account")

]

books/store/models.py
from django.db import models
from django.shortcuts import get_object_or_404
import datetime

# Create your models here.
class Account(models.Model):
    first_name = models.CharField(max_length=64) 
    last_name = models.CharField(max_length=64) 
    phone = models.CharField(max_length=16, blank=True, null=True) 
    email = models.EmailField() 
    password = models.CharField(max_length=32) 
    
    # to save the data 
    def register(self): 
        self.save() 
  
    @staticmethod
    def get_account_by_email(email): 
        try: 
            return Account.objects.get(email=email) 
        except: 
            return False
    
    def get_account_by_id(id):
        try: 
            return Account.objects.get(id=id) 
        except: 
            return False

    def isExists(self): 
        if Account.objects.filter(email=self.email): 
            return True
  
        return False


from django.db import models 
  
  
class Category(models.Model): 
    name = models.CharField(max_length=64) 
  
    @staticmethod
    def get_all_categories(): 
        return Category.objects.all() 
  
    def __str__(self): 
        return self.name 


class Book(models.Model):
    title = models.CharField(max_length=256)
    # description = models.CharField(max_length=3000, default='', blank=True, null=True)
    description = models.TextField(max_length=3000, default='', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1) 
    
    genre = models.CharField(max_length=64, default='', blank=True, null=True)
    isbn = models.IntegerField(blank=False, null=True)
    
    author = models.CharField(max_length=64, default='', blank=True, null=True )
    publisher = models.CharField(max_length=64, default='', blank=True, null=True)
    publication_date = models.DateField(blank=True, null=True)

    price = models.IntegerField(blank=False, null=True)    
    image = models.ImageField(upload_to='uploads/products/')


    @staticmethod
    def get_book_by_id(ids): 
        return get_object_or_404(Book, pk=ids)
  
    @staticmethod
    def get_all_products(): 
        return Book.objects.all() 
  
    @staticmethod
    def get_all_products_by_categoryid(category_id): 
        if category_id: 
            return Book.objects.filter(category=category_id) 
        else: 
            return Book.get_all_products()

    
class OrderItem(models.Model):
    product = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, related_name='OrderItem')
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()


class Order(models.Model): 
    items = models.ManyToManyField(OrderItem, related_name='order')
    # product = models.ForeignKey(Book, on_delete=models.CASCADE, default='')
    customer = models.ForeignKey(Account, on_delete=models.SET_NULL, related_name='order', null=True)
    price = models.IntegerField()
    address = models.CharField(max_length=64, default='', blank=True) 
    phone = models.CharField(max_length=16, default='', blank=True) 
    datetime = models.DateTimeField(default=datetime.datetime.today)
    status = models.BooleanField(default=False) 
  
    def placeOrder(self): 
        self.save() 
  
    @staticmethod
    def get_orders_by_customer(customer_id): 
        return Order.objects.filter(customer=customer_id).order_by('-date')

books/store/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms
from django.contrib.auth.hashers import make_password, check_password
from django.db.models import Q

from store.models import Account, Book, Order, OrderItem

class LoginForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder' : 'Enter your password'}))


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=64, required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(max_length=64, required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your last name'}))
    # phone = forms.CharField(max_length=11)

    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your email'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))




# Create your views here.
def index(request):
    accountID = request.session.get("account")

    books = Book.get_all_products()

    #return HttpResponse("Hello world")
    return render(request, "store/index.html", {
        "all_books" : books,
        "accountID" : accountID
    })


def login(request):
    # If we are already logged in
    accountID = request.session.get("account")
    if accountID:
        return HttpResponseRedirect(reverse("store:index"))

    if request.method == "GET":
        return render(request, "store/login.html", {
            "form" : LoginForm()
        })
    

    form = LoginForm(request.POST)

    # Validation
    if not form.is_valid():
        return render(request, "store/login.html", {
            "form" : form
        })
    
    email = form.cleaned_data["email"]
    password = form.cleaned_data["password"]
    account = Account.get_account_by_email(email)

    
    # Check if there is an account with the email in the database
    # or the password matches
    if not account or not check_password(password, account.password):
        return render(request, "store/login.html", {
            "form" : form,
            "error" : "Invalid account credentials."
        })

    # Login succesfull
    # Create a session
    request.session['account'] = account.id
    return HttpResponseRedirect(reverse("store:index"))



def signup(request):
    # If we are already logged in
    accountID = request.session.get("account")
    if accountID:
        return HttpResponseRedirect(reverse("store:index"))

    if request.method == "GET":
        accountID = request.session.get("account")
        return render(request, "store/signup.html", {
            "form": SignupForm(),
            "accountID": accountID
        })
    
    # POST

    # validation
    form = SignupForm(request.POST)
    if not form.is_valid():
        return render(request, "store/signup.html", {
            "form": form,     
        })


    # get the cleaned (proper termination of chars, no sql injection, etc) sent data
    first_name = form.cleaned_data["first_name"]
    last_name = form.cleaned_data["last_name"]
    # phone = form.cleaned_data["phone"]
    email = form.cleaned_data["email"]
    password = form.cleaned_data["password"]

    account = Account(first_name=first_name,
                        last_name=last_name,
                        phone=None,
                        email=email,
                        password=make_password(password))
    
    if account.isExists():
        form.add_error("email", "This account already exists.")

        return render(request, "store/signup.html", {
            "form": form,
        })
    
    account.register()
    request.session['account'] = account.id
    return HttpResponseRedirect(reverse("store:index"))

    

def search(request):
    search = request.POST.get('search')

    search_result = Book.objects.filter(
        Q(title__icontains=search) | Q(isbn__iexact=search) | Q(author__icontains=search)
    )



    return render(request, "store/search.html", {
        "search_querry" : search,
        "search_result" : search_result,
    })


# When the user visited the /cart route
def cart(request):
    accountID = request.session.get("account")
    # If the user is not logged in
    if not accountID:
        return HttpResponseRedirect(reverse("store:login"))

    cart = request.session.get('cart')
    if not cart:
        cart = {}
    if request.method == "GET":

        
        # Calculate total price in cart
        cart_total_price = 0
        for cart_item in cart:
            cart_total_price = cart_total_price + cart[cart_item]['total_price_int']

        is_cart_empty = not cart
        return render(request, "store/cart.html", {
            "cart" : cart,
            "cart_total_price" : format(cart_total_price, ","),
            "accountID" : accountID,
            "cart_empty" : is_cart_empty
        })




    remove = request.POST.get('removeID')
    if remove:
        if cart and remove in cart:
            cart.pop(remove)
        
        request.session['cart'] = cart 
        return HttpResponseRedirect(reverse('store:cart'))

    orderID = request.POST.get('orderId')
    quantity = int(request.POST.get('quantity-input'))
    book = Book.get_book_by_id(orderID)
    
    prev_quantity = 0
    if orderID in cart:
        prev_quantity = cart[orderID]['quantity']

    total_quantity = quantity + prev_quantity
    total_price = book.price * total_quantity

    # Add an elipsis(...) to the title if it is too long
    title = (book.title[:60] + '...') if len(book.title) > 64 else book.title
    cart_item = {
        "product_title" : title,
        "author" : book.author,
        "image" : book.image.url,
        "price" : format(book.price, ","),
        "quantity" : total_quantity,
        "total_price" : format(total_price, ","),
        "total_price_int" : total_price,
    }

    cart[orderID] = cart_item
    request.session['cart'] = cart 


    return HttpResponseRedirect(reverse('store:index'))
    
    

def book (request, bookID):
    accountID = request.session.get("account")

    book = Book.get_book_by_id(bookID)
    return render(request, "store/book.html", {
        "book" : book,
        "formated_price" : format(book.price, ","),
        "accountID" : accountID,
    })





class EditAccountForm(forms.Form):


    first_name = forms.CharField(max_length=64, widget=forms.TextInput(attrs={'placeholder': 'Enter First Name'}))
    last_name = forms.CharField(max_length=64, widget=forms.TextInput(attrs={'placeholder': 'Enter Last Name'}))
    phone = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'placeholder': 'Enter Phone Number'}))

    email = forms.EmailField(disabled=True, required=False)


    current_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'placeholder' : 'Enter Current password (Leave blank to keep unchanged)'}))
    new_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'placeholder' : 'Enter New Password'}))
    confirm_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'placeholder' : 'Confirm New Password'}))


def view_account(request):
    accountID = request.session.get("account")

    # If the user is not logged in
    if not accountID:
        return HttpResponseRedirect('store/login.html')

    my_account = Account.get_account_by_id(accountID)

    initial_values_table = {
        "first_name" : my_account.first_name,
        'last_name' : my_account.last_name,
        'phone' : my_account.phone,
        'email' : my_account.email,
    }

    
    edit_form = EditAccountForm(initial=initial_values_table)
    

    # Get
    if request.method == "GET":
        return render(request, 'store/account.html', {
            'accountID' : accountID,
            'account' : my_account,
            'edit_form' : edit_form,
        })
    
    # POST
    form = EditAccountForm(request.POST)
    if not form.is_valid():
        return render(request, "store/account.html", {
            'accountID' : accountID,
            'account' : my_account,
            'edit_form' : form,    
        })


    # get the cleaned (proper termination of chars, no sql injection, etc) sent data
    first_name = form.cleaned_data["first_name"]
    last_name = form.cleaned_data["last_name"]
    phone = form.cleaned_data["phone"]
    email = form.cleaned_data["email"]
    
    my_account.first_name = first_name
    my_account.last_name = last_name
    my_account.phone = phone


    current_password = form.cleaned_data['current_password']
    new_password = form.cleaned_data['new_password']
    confirm_password = form.cleaned_data['confirm_password']

    if current_password or new_password or confirm_password:
        if not check_password(current_password, my_account.password):
            return render(request, 'store/account.html', {
                'accountID': accountID,
                'account' : my_account,
                'edit_form' : form,
                'error' : "Incorrect Password."
            })
        
        if new_password != confirm_password:
             return render(request, 'store/account.html', {
                'accountID': accountID,
                'account' : my_account,
                'edit_form' : form,
                'error' : "Password do not match"
            })
        
        my_account.password = make_password(new_password)
    
    my_account.save()
    return HttpResponseRedirect(reverse('store:account'))
        
        


    


def checkout(request):
    # If we are not logged in
    accountID = request.session.get("account")
    if not accountID:
        return HttpResponseRedirect(reverse("store:login"))

    # Get the cart

books/store/templates/store/account.html
{% extends "store/layout.html" %}
{% load static %}


{% block extra-css %}
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> -->
    <!-- <script src="{% static 'store/book.js' %}"></script> -->

    <link rel="stylesheet" href="{% static 'store/account.css' %}">
{% endblock %}


{% block body %}
<section id="account_section">
    <div id="account_sidebar">
        <div class="account-tile">
            <div class="profile_bg">
                {{ account.first_name|make_list|first }}
            </div>
            <div class="account-tile-details">
                <div class="account-tile-name"> {{ account.first_name }} {{ account.last_name }} </div>
                <div class="account-tile-uid"> UID: {{ accountID }} </div>
            </div>
        </div>

        <div class="account_sidebar_nav">
            <a href="{% url 'store:account' %}">
                <div class="account_sidebar_nav_item" >
                    <span class="sidebar_nav_item_label"> My Account </span>
                    <span class="sidebar_nav_item_icon material-symbols-rounded nav-icons" style="color: #F2AE31;">
                        account_circle
                    </span>
                </div>
            </a>

            <a href="{% url 'store:purchases' %}">
                <div class="account_sidebar_nav_item" >
                    <span class="sidebar_nav_item_label"> My Purchases </span>
                    <span class="sidebar_nav_item_icon material-symbols-rounded nav-icons" style="color: #F1C22E;">
                        shopping_bag
                    </span>
                </div>
            </a>

            <a href="{% url 'store:cart' %}">
                <div class="account_sidebar_nav_item" >
                    <span class="sidebar_nav_item_label"> My Cart </span>
                    <span class="sidebar_nav_item_icon material-symbols-rounded nav-icons" style="color: #024A59;">
                        shopping_cart
                    </span>
                </div>
            </a>
            
           
        </div>
    </div>
    <div class="vr"></div>
    <div id="account-content">
        <h2> My Profile </h2>

        {% if error %}
            <h5 class="form-error">
                {{ error }}
            </h5>
        {% endif %}

        <form action="{% url 'store:account' %}" method="post">
            {% csrf_token %}
            {{ edit_form }}
            <input type="submit" value="Save changes">
        </form>
    </div>
    
</section>
{% endblock %}

books/store/templates/store/cart.html
{% extends "store/layout.html" %}
{% load static %}


{% block extra-css %}
    <link rel="stylesheet" href="{% static 'store/cart.css' %}">
{% endblock %}

{% block body%}
    <section style="min-height: calc(100svh - 114px); padding: 0px 144px; padding-bottom: 64px;">
        <table class="cart-table">
            <tr style="border-bottom: 1px solid #f6f6f6;  text-align: left;">
                <th style="width: 40%; text-align: left;">Product</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Action</th>
            </tr>
            {% for orderID, cart_item in cart.items %}
            <tr>
                <td>
                    <div style="display: flex;">
                        <img src="{{ cart_item.image }}" alt="{{ cart_item.product_title }}" style="width: 90px; height: 90px;  object-fit: contain;">
                        <div style="display: flex; flex-direction: column;">
                            <span style="font-weight: 600; font-family: 'Sora', sans-serif; font-size: 14px; margin-bottom: 4px;">{{ cart_item.product_title }}</span>
                            <span style="font-weight: 700; font-family: 'Sora', sans-serif; font-size: 12px; color: #024A59;"> {{ cart_item.author }}</span>
                        </div>
                    </div> 
                    
                </td>
                <td> Php {{ cart_item.price }}.00 </td>
                <td> {{ cart_item.quantity }} </td>
                <td> Php {{ cart_item.total_price }}.00 </td>
                <td> 
                    <form action="{% url 'store:cart' %}" method="post">
                        {% csrf_token %}

                        <input type="hidden" name="removeID" value="{{ orderID }}">
                        <input type="submit" value="Delete" class="cart-delete-btn">
                    </form>
                </td>

            </tr>
            <tr style="height: 8px;"></tr>
            {% endfor %}
            
        </table>

        <div class="cart-confirm-wrapper" id="stickyDiv">
            <p style="font-family: 'Montseratt', sans-serif; font-size: 16px;">Total: Php {{ cart_total_price }} </p>
            <form action="{% url 'store:checkout' %}" method="post">
                {% csrf_token %}


                {% if cart_empty %}
                    <button type="submit" class="feature-btn" disabled> Check out </button>
                {% else %}
                    <button type="submit" class="feature-btn"> Check out </button>
                {% endif %}
            </form>
        </div>
    </section>

    <script>
        const stickyDiv = document.getElementById('stickyDiv');

        // Detect if the sticky div is in sticky state (position: fixed) or not (position: relative) from the position: sticky func
        {
            let rect = stickyDiv.getBoundingClientRect()
            const isSticky = (window.innerHeight - rect.height + window.pageYOffset) <= (rect.top + window.pageYOffset)
       
            if (isSticky) {
                stickyDiv.classList.add('sticky');
            } else {
                stickyDiv.classList.remove('sticky');
            }
        }

        window.addEventListener('scroll', () => {
        let rect = stickyDiv.getBoundingClientRect()
        const isSticky = (window.innerHeight - rect.height + window.pageYOffset) <= (rect.top + window.pageYOffset)
       
            if (isSticky) {
                stickyDiv.classList.add('sticky');
            } else {
                stickyDiv.classList.remove('sticky');
            }
            // console.log("height: "  + rect.height + ", offset: " + getOffset(stickyDiv).top + " height: " + window.innerHeight + " top: " + (stickyDiv.getBoundingClientRect().top + 82))
            // console.log("Height: " + (window.innerHeight - rect.height + window.pageYOffset) + ", Offset: " + (rect.top + window.pageYOffset))
        });
    </script>
{% endblock%}

books/store/templates/store/index.html
{% extends "store/layout.html" %}
{% load static %}
{% load truncatesmart %}
{% load humanize %}


{% block extra-css %}
    <link rel="stylesheet" href="{% static 'store/index.css' %}">
{% endblock %}

{% block body%}
    <section id="hero">
        <img src="{% static 'store/hero.svg' %}" alt="BOOBS Books superstore. Bookworm's online obsessions: Books Superstore " id="hero-text">
    </section>

    <section class="all_books">
        <h2 class="section-title">All Books</h2>
        <hr>
        <div class="card-wrapper">
            {% for book in all_books %}
            <a href='{% url "store:book" bookID=book.id %}' class="card_link" style="background-color: white;">
                <div class="card">
                    <div>
                        <img src="{{ book.image.url }}" alt="{{ book.title }}" class="card_image">
                        <div>
                            <h3 class="card_title"> {{ book.title|truncatesmart:48 }} </h3>
                            <p class="card_author"> {{ book.author }} </p>
                        </div>
                    </div>
                    <div>
                        <span class="card_price"> Php {{ book.price|intcomma }}.00 </span>
                        <div class="card_action">
                            View Book
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </section>

    <script>
        const stickyDiv = document.querySelector('nav')

        // Detect if the sticky div is in sticky state (position: fixed) or not (position: relative) from the position: sticky func
        {
            let rect = stickyDiv.getBoundingClientRect()
            const isSticky = window.pageYOffset > 0
       
            if (isSticky) {
                stickyDiv.classList.add('sticky');
            } else {
                stickyDiv.classList.remove('sticky');
            }
        }

        window.addEventListener('scroll', () => {
        let rect = stickyDiv.getBoundingClientRect()
        const isSticky = window.pageYOffset > 0
       
            if (isSticky) {
                stickyDiv.classList.add('sticky');
            } else {
                stickyDiv.classList.remove('sticky');
            }
            // console.log("height: "  + rect.height + ", offset: " + getOffset(stickyDiv).top + " height: " + window.innerHeight + " top: " + (stickyDiv.getBoundingClientRect().top + 82))
            // console.log("Height: " + (window.innerHeight - rect.height + window.pageYOffset) + ", Offset: " + (rect.top + window.pageYOffset))
        });
    </script>
{% endblock%}

books/store/templates/store/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Google Fonts API -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Sora:400,700' rel='stylesheet' type='text/css'>

    <!-- Google Icons API -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'store/styles.css' %}">
    
    {% block extra-css %}
    {% endblock %}

    <title>BOOBS Book store</title>
    <link rel="icon" type="image/x-icon" href="{% static 'store/favicon.svg' %}">
</head>
<body>
    <nav>
        {% if custom_nav_title %}
            <a href="{% url 'store:index' %}" class="nav-title">{{ custom_nav_title }}</a>
        {% else %}
            <a href="{% url 'store:index' %}" class="nav-title">BOOBS</a>
        {% endif %}

        <form action="{% url 'store:search' %}" method="post" class="book-search-form">
            {% csrf_token %}

            <input type="search" placeholder="Search for books" class="book-search-input", name="search" value="{{ search_querry }}">
            <button type="submit">
                <span class="material-symbols-rounded">
                    search
                </span>
            </button>
        </form>

        <div class="nav-right-btns">
            <a class="material-symbols-rounded nav-icons" href="{% url 'store:cart' %}">
                shopping_cart
            </a>
            {% if accountID %}
            <div class="dropdown">
                <span class="material-symbols-rounded nav-icons">
                    account_circle
                </span>
                <div class="dropdown-content">
                    <div class="dropdown-item">
                        <a href="{% url 'store:account' %}"> My Account </a>
                    </div>
                    <div class="dropdown-item">
                        <a href="{% url 'store:purchases' %}"> My Purchases </a>
                    </div>
                    <div class="dropdown-item">
                        <a href="{% url 'store:logout' %}"> Logout </a>
                    </div>
                    
                </div>
            </div>
            {% else %}
            <div style="display: flex; flex-direction: row; gap: 16px; margin-left: 32px; vertical-align: middle;">
                <a href="{% url 'store:login' %}" style="margin-top: auto; margin-bottom: auto;"> Login </a>
                <a href="{% url 'store:signup' %}" style="margin-top: auto; margin-bottom: auto;"> Sign up </a>
            </div>
            {% endif %}
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <footer>
        <div class="footer-left">
            <h1 class="footer-title" style="margin-bottom: 16px;">BOOBS</h1>
            <p> Got something big? </p>
            <p>Contact us: </p>
            <br>
            <p style="font-weight: 700;">092748324509</p>
            <br>
            <br>
            <p>For inquiries/concerns</p>
            <p>get in touch with us at:</p>
            <br>
            <a href="https://www.boobssuperstore.com" style="color: white; font-family: 'Montserrat', sans-serif; font-size: 16px;">www.boobssuperstore.com</a>
        </div>
        <!-- <div class="vr" style="background-color: #1E3439;"></div> -->
        <div class="footer_right" style="border-left: 1px solid #1E3439;">
            <h5 class="footer_right_title">
                About this project
            </h5>
            <br>
            <p>

            This is an ecommerce website for our final project in CMPSC 117 Web Development <br><br>
            Group members:
            <ul style="padding: 16px;">
                <li>Baloaloa Jansen    </li>
                <li>Dorilag Eunice Lyka </li>
                <li>Ubado Seah           </li>
                <li>Valdez Audray Mae    </li>
            </ul>
            </p>
        </div>
    </footer>
</body>
</html>

books/store/templates/store/login.html
{% extends "store/layout.html" %}
{% load static %}


{% block body %}
    <section id="hero">
        <img src="{% static 'store/hero.svg' %}" alt="BOOBS Books superstore. Bookworm's online obsessions: Books Superstore " id="hero-text">
    
        <div class="form-card">
            <p class="form-card-title"> Login </p>

            {% if error %}
            <h5 class="form-error">
                {{ error }}
            </h5>
            {% endif %}
            <form action="{% url 'store:login' %}", method="post">
                {% csrf_token %}
                
                {{  form }}
        
                <input type="submit" value="Login" style="margin-top: 40px;">
            </form>
            <div style="display: flex; flex-direction: row; margin: 0px auto; margin-top: 24px;">
                <p style="font-family: 'Montserrat', sans-serif; font-size: 14px;">Don’t have an account? <a href="{% url "store:signup" %}" style="color: #F2AE31; font-weight: bold; font-family: 'Montserrat', sans-serif; font-size: 14px;">Register now</a>
                </p>
            </div>
        </div>
    </section>

    
{% endblock %}

books/store/templates/store/signup.html
{% extends "store/layout.html" %}
{% load static %}


{% block body%}
    <section id="hero">
        <img src="{% static 'store/hero.svg' %}" alt="BOOBS Books superstore. Bookworm's online obsessions: Books Superstore " id="hero-text">
    
        <div class="form-card">
            <p class="form-card-title"> Sign up </p>

            {% if error %}
            <h5 class="form-error">
                {{ error }}
            </h5>
            {% endif %}

            <form action="{% url 'store:signup' %}" id="signup-form" method="post">
                {% csrf_token %}
                
                {{  form }}
        
                <input type="submit" value="Register">
            </form>
            <div style="display: flex; flex-direction: row; margin: 0px auto; margin-top: 24px;">
                <p style="font-family: 'Montserrat', sans-serif; font-size: 14px;">Don’t have an account? <a href="{% url "store:signup" %}" style="color: #F2AE31; font-weight: bold; font-family: 'Montserrat', sans-serif; font-size: 14px;">Register now</a>
                </p>
            </div>
        </div>
    </section>
{% endblock%}